name: Java CI

on: [push, pull_request]

jobs:
  build-and-run-unit-test:
    runs-on: ubuntu-latest
    steps:
      # Pull the code from the repository.
      - name: Pull the code from the repository
        uses: actions/checkout@v3
      # Build the project with Maven.
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compilation with Maven and Unit test
        run: mvn package && mvn test